rvm:
    - "1.8.7"
    - "1.9.3"
    - "2.0.0"
    - "jruby-1.7.6"
env:
    - FLEX_COLUMNS_AR_TEST_VERSION=3.0.20 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=mysql
    - FLEX_COLUMNS_AR_TEST_VERSION=3.0.20 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=postgres
    - FLEX_COLUMNS_AR_TEST_VERSION=3.0.20 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=sqlite
    - FLEX_COLUMNS_AR_TEST_VERSION=3.1.12 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=mysql
    - FLEX_COLUMNS_AR_TEST_VERSION=3.1.12 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=postgres
    - FLEX_COLUMNS_AR_TEST_VERSION=3.1.12 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=sqlite
    - FLEX_COLUMNS_AR_TEST_VERSION=3.2.15 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=mysql
    - FLEX_COLUMNS_AR_TEST_VERSION=3.2.15 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=postgres
    - FLEX_COLUMNS_AR_TEST_VERSION=3.2.15 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=sqlite
    - FLEX_COLUMNS_AR_TEST_VERSION=4.0.1 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=mysql
    - FLEX_COLUMNS_AR_TEST_VERSION=4.0.1 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=postgres
    - FLEX_COLUMNS_AR_TEST_VERSION=4.0.1 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=sqlite
before_script:
    - mysql -e 'create database myapp_test;'
    - psql -c 'create database myapp_test;' -U postgres
matrix:
    exclude:
        # ActiveRecord 4.x doesn't support Ruby 1.8.7
        -   rvm: 1.8.7
            env: FLEX_COLUMNS_AR_TEST_VERSION=4.0.1 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 1.8.7
            env: FLEX_COLUMNS_AR_TEST_VERSION=4.0.1 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 1.8.7
            env: FLEX_COLUMNS_AR_TEST_VERSION=4.0.1 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=sqlite
        # There's a bug in ActiveRecord 3.1.x that makes it incompatible with Ruby 2.0
        -   rvm: 2.0.0
            env: FLEX_COLUMNS_AR_TEST_VERSION=3.1.12 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=mysql
        -   rvm: 2.0.0
            env: FLEX_COLUMNS_AR_TEST_VERSION=3.1.12 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=postgres
        -   rvm: 2.0.0
            env: FLEX_COLUMNS_AR_TEST_VERSION=3.1.12 FLEX_COLUMNS_TRAVIS_CI_DATABASE_TYPE=sqlite
